version: "3.3"

services:
  app:
    build:
      context: "./src"
    env_file: "./src/.env"
    volumes:
      - ./src:/usr/app/
    depends_on:
      - database
    ports:
      - "8000:8000"
    
  database:
    image: mysql:5.6
    restart: always
    # For the sake of simplicity and time, we are using a hardcoded password here.
    environment:
      MYSQL_ROOT_PASSWORD: v25xhycLlRY3sV7Z
      MYSQL_DATABASE: "exercise"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
