"""Fix date_added field name

Revision ID: 734639758dc5
Revises: 0ef0c1c1bd0e
Create Date: 2024-03-04 22:35:49.855066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '734639758dc5'
down_revision = '0ef0c1c1bd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=False))
        batch_op.drop_index('uri')
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.drop_column('uri')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('uri', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('uri', ['uri'], unique=True)
        batch_op.drop_column('date_added')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
